# Generated by Django 3.0 on 2020-02-26 15:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('datecreated', models.DateTimeField(default=datetime.datetime(2020, 2, 26, 16, 46, 51, 121582))),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
