# Generated by Django 3.0 on 2020-02-26 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vendorsaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 16, 50, 6, 611056)),
        ),
        migrations.AlterField(
            model_name='vendorsaccount',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 16, 50, 6, 623556)),
        ),
    ]
