# Generated by Django 3.0 on 2020-02-26 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200226_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 17, 34, 50, 306966)),
        ),
        migrations.AlterField(
            model_name='vendorsaccount',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 17, 34, 50, 322566)),
        ),
    ]
